### PR TITLE
Officially templatize

### PR DESCRIPTION
**Pull request by tianon**
```console
$ ./update.sh
+ sed 's!SUITE!jessie!g' Dockerfile.template-curl
+ sed 's!SUITE!jessie!g' Dockerfile.template-scm
+ sed 's!SUITE!jessie!g' Dockerfile.template
+ sed 's!SUITE!sid!g' Dockerfile.template-curl
+ sed 's!SUITE!sid!g' Dockerfile.template-scm
+ sed 's!SUITE!sid!g' Dockerfile.template
+ sed 's!SUITE!squeeze!g' Dockerfile.template-curl
+ sed 's!SUITE!squeeze!g' Dockerfile.template-scm
+ sed 's!SUITE!squeeze!g' Dockerfile.template
+ sed 's!SUITE!stretch!g' Dockerfile.template-curl
+ sed 's!SUITE!stretch!g' Dockerfile.template-scm
+ sed 's!SUITE!stretch!g' Dockerfile.template
+ sed 's!SUITE!wheezy!g' Dockerfile.template-curl
+ sed 's!SUITE!wheezy!g' Dockerfile.template-scm
+ sed 's!SUITE!wheezy!g' Dockerfile.template
```

### CODE REVIEW

**Comment by tianon** [comment]
We'll still need to figure out how/if https://github.com/docker-library/buildpack-deps/pull/27 fits into this. :confused:

**Comment by tianon** [comment]
It's figured now -- we have a new problem (tag sprawl like crazy :innocent:).

**Comment by tianon** [comment]
With this change:
```console
$ bashbrew list --uniq buildpack-deps
buildpack-deps:jessie-curl
buildpack-deps:jessie-scm
buildpack-deps:jessie
buildpack-deps:precise-curl
buildpack-deps:precise-scm
buildpack-deps:precise
buildpack-deps:sid-curl
buildpack-deps:sid-scm
buildpack-deps:sid
buildpack-deps:squeeze-curl
buildpack-deps:squeeze-scm
buildpack-deps:squeeze
buildpack-deps:stretch-curl
buildpack-deps:stretch-scm
buildpack-deps:stretch
buildpack-deps:trusty-curl
buildpack-deps:trusty-scm
buildpack-deps:trusty
buildpack-deps:utopic-curl
buildpack-deps:utopic-scm
buildpack-deps:utopic
buildpack-deps:vivid-curl
buildpack-deps:vivid-scm
buildpack-deps:vivid
buildpack-deps:wheezy-curl
buildpack-deps:wheezy-scm
buildpack-deps:wheezy
buildpack-deps:wily-curl
buildpack-deps:wily-scm
buildpack-deps:wily
```

**Comment by tianon** [comment]
Which I suppose I'm pretty much OK with for now.

**Comment by tianon** [comment]
(from 18 to 30 uniques all at once)

**Comment by yosifkit** [comment]
LGTM

**Comment by Moghedrin** [comment]
LGTM

**Pull request merged**
