### PR TITLE
Add Ubuntu Lunar Lobster 23.04

### PR DESCRIPTION
**Pull request by vicamo**
Signed-off-by: You-Sheng Yang (vicamo) <vicamo@gmail.com>

### CODE REVIEW

**Comment by yosifkit** [comment]
Ubuntu 23.04 is currently a development release. We are not going to add this before `23.04` is released, so this will need to wait until then (April 2023).

**Comment by tianon** [comment]
> Never mind, I was wrong. We do have unstable releases in `buildpack-deps` images.

This is my bad -- originally we had official use cases for unstable releases (like the old `openjdk` images), but now I think it's less defensible than previously.  I'd like to remove `buildpack-deps:sid`, but I'm not sure how widely used it is _outside_ of official images, and I think beyond that explicit named releases probably are mostly harmless?  :sweat_smile:

**Comment by vicamo** [comment]
> > Never mind, I was wrong. We do have unstable releases in `buildpack-deps` images.
> 
> This is my bad -- originally we had official use cases for unstable releases (like the old `openjdk` images), but now I think it's less defensible than previously. I'd like to remove `buildpack-deps:sid`, but I'm not sure how widely used it is _outside_ of official images, and I think beyond that explicit named releases probably are mostly harmless? 😅

https://salsa.debian.org/ci-team/autopkgtest/-/blob/master/.gitlab-ci.yml
Hi, unstable and devel tags are critical to people who develop software. It's the base environment for some testing frameworks just like the latest tags do. Please do add these tags as long as they become available.

**Comment by tianon** [comment]
Sorry, I should've been more explicit - if we could go back, I probably wouldn't add them to `buildpack-deps`, but they definitely still make sense in `debian` and `ubuntu` (although the latter is now entirely up to Canonical's discretion whether they will continue publishing those), and that's the image being used in that `.gitlab-ci.yml`. :smile:

At this point, we've already got them here and I think it probably makes sense to continue for consistency and because it's really useful to have at least the `-curl` and `-scm` variants for all released, to-be-released, and in-development suites of these distributions even if they aren't widely used within the official images directly.

**Pull request merged**
