### PR TITLE
Split up micro images even further into explicit "curl" and "scm" variants

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Documentation in https://github.com/docker-library/docs/pull/140

**Comment by tianon** [comment]
cc @proppy

**Comment by yosifkit** [comment]
LGTM

**Comment by yosifkit** [comment]
On a slightly related note, we should drop meta packages (like `build-essential`) and install things explicitly (maybe even with `--no-install-recommends`).

**Comment by tianon** [comment]
Ah, I don't know if the definition of `build-essential` has changed, or if I just never looked into it deeply enough (because it was my understanding that it was supposed to be just the essential packages required to compile basic software), but it clearly isn't, and is more specific to Debian packaging: (https://packages.debian.org/sid/build-essential)
> This package contains an informational list of packages which are considered essential for building Debian packages. This package also depends on the packages on that list, to make it easy to have the build-essential packages installed.

Clearly not at all what we're after, and thus I agree with replacing it with more specific deps.  I'm not 100% sold on `--no-install-recommends` in the base `Dockerfile`s, but I'd be interested what packages we lose by doing so such that we can make an informed decision either way.

**Pull request merged**
