### PR TITLE
Add ubuntu:yakkety variant

### PR DESCRIPTION
**Pull request by vicamo**

### CODE REVIEW

**Comment by vicamo** [comment]
Newly added Dockerfiles are generated from `update.sh`.

**Comment by tianon** [comment]
Thanks! :+1:

**Comment by vicamo** [comment]
@tianon any thing to do to kick off an yakkety build? Still unavailable in https://hub.docker.com/r/library/buildpack-deps/tags/

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/2321 :+1:

**Pull request merged**
