### PR TITLE
Add libgeoip-dev

### PR DESCRIPTION
**Pull request by mattrobenolt**

### CODE REVIEW

**Comment by yosifkit** [comment]
Are there popular libraries that use this (ruby gems, python packages, npm packages, perl modules)?

**Comment by md5** [comment]
https://rubygems.org/gems/geoip/versions/1.6.1

> TOTAL DOWNLOADS
> 1,765,240
> FOR THIS VERSION
> 38,063

https://www.npmjs.com/package/geoip

> 10,466 downloads in the last month

I'm sure there are others for other languages as well.

**Comment by md5** [comment]
PHP has one as well that I've had to enable on a project or two.

**Comment by mattrobenolt** [comment]
And Python: https://pypi.python.org/pypi/GeoIP/

> Downloads (All Versions):
> 187 downloads in the last day
> 2038 downloads in the last week
> 9161 downloads in the last month

**Comment by mattrobenolt** [comment]
Oh, and I guess the even more popular newer version: https://pypi.python.org/pypi/geoip2

> Downloads (All Versions):
> 1210 downloads in the last day
> 13562 downloads in the last week
> 65931 downloads in the last month

**Comment by tianon** [comment]
Niiice; sounds good.

LGTM

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
