### PR TITLE
Add libpng-dev

### PR DESCRIPTION
**Pull request by mattrobenolt**
We have a bunch of other imaging libs, so should probably have png support too.

### CODE REVIEW

**Comment by tianon** [comment]
In hindsight, this seems like a pretty obvious oversight. :+1:

LGTM

**Comment by mattrobenolt** [comment]
Lemme add to the other bases.

**Comment by tianon** [comment]
Although, this needs to be added to the template instead of just to jessie.

**Comment by tianon** [comment]
:+1:

**Comment by mattrobenolt** [comment]
@tianon Added errywhere.

**Comment by tianon** [comment]
LGTM

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
