### PR TITLE
Make arches list space separated for easier looping/awking

### PR DESCRIPTION
**Pull request by yosifkit**

### CODE REVIEW

**Comment by tianon** [comment]
Do you have some sample output to prove it still works? :slightly_smiling_face:

**Comment by tianon** [comment]
(I cancelled Travis so we don't waste their resources on building this)

**Comment by yosifkit** [comment]
```console
$ # on branch "join"
$ ./generate-stackbrew-library.sh > buildpack-new
$ git checkout master
$ ./generate-stackbrew-library.sh > buildpack-old
$ diff buildpack-old buildpack-new
1c1
< # this file is generated via https://github.com/docker-library/buildpack-deps/blob/f243e010fec2494fa6f119298da2c37ef4031baf/generate-stackbrew-library.sh
---
> # this file is generated via https://github.com/docker-library/buildpack-deps/blob/ac51851510ce191b9808a2bb6780fff23aef5dd3/generate-stackbrew-library.sh
```

**Comment by tianon** [comment]
See also https://github.com/docker-library/buildpack-deps/pull/59.

**Pull request merged**
