### PR TITLE
Add stretch

### PR DESCRIPTION
**Pull request by vicamo**
Just copy jessie to the next Debian testing release -- stretch.

### CODE REVIEW

**Comment by vicamo** [comment]
Note that even though stretch [has been](https://github.com/tianon/docker-brew-debian/commit/9dfdde0c647a7641886b2831f3f2cbcf64a85c1a) added to [docker-brew-debian](https://github.com/tianon/docker-brew-debian), it's still [not yet](https://registry.hub.docker.com/_/debian/) built.

**Comment by vicamo** [comment]
update: docker-brew-debian has stretch now.

**Comment by tianon** [comment]
LGTM

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
